# -*- coding: utf-8 -*-
"""Publish the unlockable sentences to the recombination drill.

    python3 tools/build_drill.py

WHAT IS AND IS NOT IN HERE
Only the sentences. No conjugations, no transformations, no verb data — the drill page loads
`GRAMMAR_LAB/data/verbs.js` and `engine.js` directly and does all of that live. That is
deliberate: the conjugation logic exists once, in the engine, and a correction to a stem in
verbs.js reaches the drill on the next page load with no rebuild. Precomputing the
transformations here would fork the paradigm into a second copy that goes stale silently,
which is the failure this project has already paid for once with romanization.

WHY THE WORD REQUIREMENTS SHIP TOO
`unlock_day` alone would be enough to gate the drill on the schedule. But the study desk lets
you mark words known ahead of schedule — words picked up at home — and those should pull
sentences forward, which is most of the point of marking them. So each sentence carries the
`study_order` of every word it needs. The drill can then ask the real question ("do I know
every word in this?") instead of the proxy one ("has enough time passed?").

Requirements are computed with `sequence.py`'s own index rather than a second implementation.
That matters more than it looks: coverage has three routes (exact word, Verb Lab surface form,
known word plus a short inflectional tail) and the length guard on the third one is the
difference between a readable sentence and one that only looks readable.
"""
import csv, json, os, sys
from datetime import date

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..'))
sys.path.insert(0, HERE)

import sequence

OUT = os.path.join(ROOT, 'STUDY', 'data', 'sentences.js')

FIELDS = ['guid', 'day', 'order', 'telugu', 'roman', 'english', 'register', 'need']


def build():
    words, sents, vf = sequence.load()
    index = sequence.build_index(words, vf)
    reqs, _ = sequence.sentence_requirements(sents, words, index)

    # word index -> study_order, so the drill can compare against "words introduced so far"
    # and against the marked-known set without shipping the word master a second time.
    order_of = {i: int(w['study_order']) for i, w in enumerate(words)
                if str(w['study_order']).isdigit()}

    rows, skipped, templates = [], 0, 0
    for si, s in enumerate(sents):
        if not str(s['unlock_day']).isdigit():
            continue                       # never unlocks: contains words not in the master
        # A handful of corpus rows are fill-in-the-blank templates rather than sentences —
        # "nēnu ______ ni." There is nothing to produce and nothing to transform, and blanking
        # a word in an already-blanked frame yields an exercise with two blanks and one answer.
        if '__' in s['telugu'] or '__' in s['roman']:
            templates += 1
            continue
        need, gaps = reqs[si]
        if gaps:
            skipped += 1
            continue
        orders = sorted({order_of[i] for i in need if i in order_of})
        if len(orders) != len(need):
            skipped += 1                   # a required word has no position; cannot be gated
            continue
        rows.append([s['guid'], int(s['unlock_day']), int(s['unlock_order']),
                     s['telugu'], s['roman'], s['english'],
                     s.get('register', ''), orders])

    rows.sort(key=lambda r: r[2])

    data = {
        'generated': date.today().isoformat(),
        'fields': FIELDS,
        'counts': {'sentences': len(rows),
                   'lastDay': max((r[1] for r in rows), default=0),
                   'corpus': len(sents)},
        'sentences': rows,
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('/* Generated by tools/build_drill.py from data/master_sentences.tsv.\n'
                ' * Do not edit. Rows are arrays in SENTENCE_DATA.fields order.\n'
                ' * `need` is the study_order of every word the sentence requires. */\n')
        f.write('const SENTENCE_DATA = '
                + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n')

    c = data['counts']
    print(f'{OUT.replace(ROOT + os.sep, "")}  {os.path.getsize(OUT) / 1024:.0f} KB')
    print(f'  {c["sentences"]} unlockable sentences of {c["corpus"]} in the corpus, '
          f'through day {c["lastDay"]}')
    if skipped:
        print(f'  {skipped} dropped — dated but with an unresolvable or unpositioned word')
    if templates:
        print(f'  {templates} dropped — fill-in-the-blank templates, not sentences')
    avg = sum(len(r[7]) for r in rows) / len(rows) if rows else 0
    print(f'  {avg:.1f} words required per sentence on average')


if __name__ == '__main__':
    build()
