# -*- coding: utf-8 -*-
"""Publish the verb form -> root map to the browser.

    python3 tools/build_stems.py

WHY THE BROWSER NEEDS THIS
The analyzer's chunk miner has to tell two kinds of repeated frame apart:

    నాకు ___ కావాలి        the slot varies by *word*      — a lexical frame, worth a card
    నేను ___ వెళ్తాను       the slot varies by *verb form*  — a conjugation, already in the Lab

They look identical to an n-gram counter. What separates them is knowing that వెళ్ళాను and
వెళ్తాను are the same verb, which needs a form -> root map. tools/verbforms.json already has
one, built from the audited paradigms, so this only reshapes it for the page.

SIZE
verbforms.json is 279 KB because every entry carries lemma and form-name as well. The page
needs neither — only "are these two surface forms the same verb". Indexing the 54 roots into an
array and pointing each form at an integer cuts it to about 100 KB, against the 263 KB of
words.js the page already loads.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..'))
SRC = os.path.join(HERE, 'verbforms.json')
OUT = os.path.join(ROOT, 'STUDY', 'data', 'stems.js')


def main():
    forms = json.load(open(SRC, encoding='utf-8'))
    roots = sorted({v['root'] for v in forms.values()})
    idx = {r: i for i, r in enumerate(roots)}
    # form -> index of its root. Surface form is the key because that is what the miner has.
    table = {k: idx[v['root']] for k, v in sorted(forms.items())}

    payload = {'roots': roots, 'forms': table}
    body = json.dumps(payload, ensure_ascii=False, separators=(',', ':'))

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('/* Generated by tools/build_stems.py — do not edit.\n'
                '   Verb surface form -> root, so the chunk miner can tell a lexical frame from a\n'
                '   conjugation. Regenerate after any change to the Verb Lab paradigms. */\n')
        f.write('const STEM_DATA = ' + body + ';\n')

    print(f'{len(table):,} forms across {len(roots)} roots -> {OUT}')
    print(f'  {os.path.getsize(OUT) / 1024:.0f} KB')


if __name__ == '__main__':
    main()
