# -*- coding: utf-8 -*-
"""Publish the word master to the site as a browsable, markable list.

    python3 tools/build_studydata.py

WHY THIS READS THE MASTER AND NOT anki/import_words.txt
The obvious source is the Anki file, since that is literally the list of cards. It is the
wrong one. `anki/import_words.txt` is disposable output: five fields, no study_order, no
study_day, no island, no lesson, no flags — everything that makes the list navigable is
dropped on the way out because Anki has no use for it. Both files come from
data/master_words.tsv, so reading the master gives the same words in the same order with the
context intact, and keeps the "masters are the source of truth" rule unbroken.

WHY A .js FILE AND NOT .json
The rest of the site loads data through <script> tags (see GRAMMAR_LAB/data/verbs.js).
fetch() of a local file is blocked by CORS under file://, so a JSON file would make the page
work on GitHub Pages and break when the folder is opened directly. A script tag works in both.

WHY ROWS ARE ARRAYS
2,215 words × 12 fields. Repeating the key names on every row roughly doubles the file for no
benefit; `FIELDS` is declared once and the page hydrates rows into objects on load.

The guid is the join key, and the reason this list can carry hand-marked state at all: it is a
hash of the Telugu script (tools/ids.py), so it survives re-sequencing, re-export and
re-import. Marking a word known here still means the same word after the next rebuild.
"""
import csv, glob, html, json, os, re
from collections import Counter
from datetime import date

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..'))
WORDS = os.path.join(ROOT, 'data', 'master_words.tsv')
SENTS = os.path.join(ROOT, 'data', 'master_sentences.tsv')
OUT = os.path.join(ROOT, 'STUDY', 'data', 'words.js')
LESSONS_OUT = os.path.join(ROOT, 'STUDY', 'data', 'lessons.js')

WORDS_PER_DAY = 15                      # must match tools/sequence.py

FIELDS = ['guid', 'order', 'day', 'telugu', 'roman', 'english',
          'pos', 'island', 'lesson', 'example', 'flags', 'source']

# Why a word never reaches the deck, in words rather than flag names. Anything flagged with one
# of these is held out by both sequence.py and build_exports.py, so it has no study_order and
# no day — but it should still be *visible* here, or the page silently disagrees with the
# master about how many words exist.
HELD_OUT = {
    'needs-script': 'no Telugu script yet',
    'no-script': 'no Telugu script yet',
    'kannada-script': 'source printed it in Kannada script',
    'devanagari-script': 'source printed it in Devanagari',
    'bound-suffix': 'an ending, not a free-standing word',
    'english-respelled': 'an English word in Telugu letters',
    'no-english': 'no gloss yet',
}


def build_lessons(words):
    """The course lesson list, with how many deck words each one taught.

    Generated rather than typed into the dashboard, so lesson 21 shows up on its own instead
    of the home page quietly disagreeing with the course. Titles come from each page's own h1,
    which is the heading a reader already associates with that lesson."""
    per = Counter(w['lesson'] for w in words if w['lesson'])
    out = []
    for path in sorted(glob.glob(os.path.join(ROOT, 'LEARNING_GUIDE', 'lessons', 'lesson-*.html'))):
        num = re.search(r'lesson-(\d+)', os.path.basename(path)).group(1)
        src = open(path, encoding='utf-8').read()
        m = re.search(r'<h1[^>]*>(.*?)</h1>', src, re.S)
        title = html.unescape(re.sub(r'<[^>]+>', '', m.group(1))).strip() if m else f'Lesson {num}'
        out.append([num, title, os.path.basename(path), per.get(num, 0)])

    with open(LESSONS_OUT, 'w', encoding='utf-8') as f:
        f.write('/* Generated by tools/build_studydata.py. Do not edit.\n'
                ' * [number, title, filename, words taught] */\n')
        f.write('const LESSON_DATA = ' +
                json.dumps(out, ensure_ascii=False, separators=(',', ':')) + ';\n')
    return out


def rows(path):
    return list(csv.DictReader(open(path, encoding='utf-8'), delimiter='\t'))


def held_reason(flags):
    for f in flags.split():
        if f in HELD_OUT:
            return HELD_OUT[f]
    return ''


def build():
    words, sents = rows(WORDS), rows(SENTS)

    # study_order first, then everything held out — in one list, so the page can show the whole
    # master and be explicit about what is excluded rather than quietly showing 2,103 of 2,215.
    def key(w):
        o = w['study_order']
        return (0, int(o)) if str(o).isdigit() else (1, w['id'])

    out = []
    for w in sorted(words, key=key):
        o = int(w['study_order']) if str(w['study_order']).isdigit() else 0
        d = int(w['study_day']) if str(w['study_day']).isdigit() else 0
        out.append([w['guid'], o, d, w['telugu'], w['roman'], w['english'],
                    w['pos'], w['island'], w['lesson'], w['example'],
                    held_reason(w['flags']), w['source']])

    # Sentences becoming fully readable on each day — the payoff for a day's vocabulary, and the
    # only number on the page that answers "why these fifteen words".
    unlocks = Counter(int(s['unlock_day']) for s in sents
                      if str(s['unlock_day']).isdigit())

    data = {
        'generated': date.today().isoformat(),
        'rate': WORDS_PER_DAY,
        'fields': FIELDS,
        'counts': {
            'words': len(words),
            'scheduled': sum(1 for r in out if r[1]),
            'heldOut': sum(1 for r in out if not r[1]),
            'lastDay': max((r[2] for r in out), default=0),
            'sentences': len(sents),
            'sentencesDated': sum(unlocks.values()),
        },
        'unlocks': {str(k): v for k, v in sorted(unlocks.items())},
        'words': out,
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    body = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('/* Generated by tools/build_studydata.py from data/master_words.tsv.\n'
                ' * Do not edit. Rows are arrays in WORD_DATA.fields order. */\n')
        f.write('const WORD_DATA = ' + body + ';\n')

    lessons = build_lessons(words)

    c = data['counts']
    print(f'{OUT.replace(ROOT + os.sep, "")}  {os.path.getsize(OUT) / 1024:.0f} KB')
    print(f'  {c["words"]} words — {c["scheduled"]} scheduled over {c["lastDay"]} days, '
          f'{c["heldOut"]} held out')
    print(f'  {c["sentencesDated"]} of {c["sentences"]} sentences carry an unlock day')
    print(f'  {len(lessons)} lessons -> {LESSONS_OUT.replace(ROOT + os.sep, "")}')


if __name__ == '__main__':
    build()
