# -*- coding: utf-8 -*-
"""Find cards whose English prompt does not identify one answer.

    python3 tools/check_glosses.py            # write review/gloss-collisions.md
    python3 tools/check_glosses.py --top 300  # only the part of the queue in reach

WHY THIS EXISTS
The word deck is English -> Telugu production. That direction only works if the prompt picks
out exactly one answer, and nothing in the pipeline was checking that it did. Two cards
glossed "eat" are not two cards; they are one unanswerable card shown twice, and the learner
gets marked wrong for producing a correct Telugu word.

They surfaced the way you would expect — one at a time, mid-review, as "this card is weird".
That is an expensive way to find 196 of them.

WHAT COUNTS AS A COLLISION
Byte-identical glosses only. A parenthetical is a real disambiguator: "you (informal — close
friends/family only)" and "you (formal / plural — the safe default)" are answerable cards and
must not be reported, or the report drowns in false positives and stops being read.

The groups are sorted by the earliest position in each, because that is when it bites. A
collision at 1,400 is a problem for next year; one at 42 is a problem this week.

TRIAGE IS NOT AUTOMATABLE, so this only reports. The categories need different fixes and
several need a native speaker:

  synonyms          nīḷḷu / nīru "water"      -> which is the default, which is marked
  loan doublets     skūl / pāṭhaśāla          -> tag the loanword or drop it
  derived forms     tinu / tinaḍāniki "eat"   -> the derived one should say what it is
  spelling variants drākṣa / tradākṣa         -> usually a source typo; merge or drop
  grade pairs       nēruga / nērugā           -> the -gā adverbial the course teaches
"""
import argparse, collections, csv, os
from datetime import date

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..'))
WORDS = os.path.join(ROOT, 'data', 'master_words.tsv')
OUT = os.path.join(ROOT, 'review', 'gloss-collisions.md')


def load():
    with open(WORDS, encoding='utf-8', newline='') as f:
        return [r for r in csv.DictReader(f, delimiter='\t')
                if str(r.get('study_order', '')).strip().isdigit()]


def collisions(rows):
    g = collections.defaultdict(list)
    for r in rows:
        key = (r['english'] or '').strip().lower()
        if key:
            g[key].append(r)
    out = [(k, sorted(v, key=lambda r: int(r['study_order'])))
           for k, v in g.items() if len(v) > 1]
    out.sort(key=lambda kv: int(kv[1][0]['study_order']))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--top', type=int, default=0,
                    help='only report groups whose first card is within this many positions')
    a = ap.parse_args()

    rows = load()
    groups = collisions(rows)
    if a.top:
        groups = [g for g in groups if int(g[1][0]['study_order']) <= a.top]

    cards = sum(len(v) for _, v in groups)
    both_early = [g for g in groups if int(g[1][1]['study_order']) <= 300]

    lines = [
        '# Gloss collisions',
        '',
        f'Generated by `tools/check_glosses.py` on {date.today().isoformat()}. Do not edit — '
        'fix the glosses in `data/overrides_words.tsv` and re-run.',
        '',
        f'**{len(groups)} groups, {cards} cards** share a byte-identical English prompt. The deck '
        'is English → Telugu production, so each of these is one unanswerable card shown twice: '
        'you produce a correct Telugu word and get marked wrong.',
        '',
        f'**{len(both_early)} groups have both cards inside the first 300 positions** — those bite '
        'soonest and are worth fixing first. Where one card is early and the other is a thousand '
        'positions away, the collision is real but months off.',
        '',
        'Sorted by the earliest position in each group.',
        '',
    ]

    for key, v in groups:
        first = int(v[0]['study_order'])
        mark = ' ⚠' if int(v[1]['study_order']) <= 300 else ''
        lines.append(f'### {first} · "{key}"{mark}')
        lines.append('')
        lines.append('| pos | day | romanization | Telugu | source | flags |')
        lines.append('|---|---|---|---|---|---|')
        for r in v:
            lines.append(f'| {r["study_order"]} | {r["study_day"]} | `{r["roman"]}` | '
                         f'{r["telugu"]} | {r["source"]} | {r["flags"]} |')
        lines.append('')

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f'{len(groups)} collision groups, {cards} cards')
    print(f'  {len(both_early)} with both cards inside the first 300')
    print(f'  -> {os.path.relpath(OUT, ROOT)}')
    for key, v in groups[:8]:
        print(f'    {v[0]["study_order"]:>5}  "{key}"  ' +
              ' / '.join(r['roman'] for r in v))


if __name__ == '__main__':
    main()
